### PR TITLE
35 work on nav bar and project theme

### PR DESCRIPTION
**Pull request by robertdavidwest**

### CODE REVIEW

**Comment by robertdavidwest** [comment]
Added color theme to project: 

image

you change the reference for these at any time. Here's samples :https://mui.com/material-ui/customization/color/#picking-colors

now you can use these colors anywhere in the app just do `color='primary.dark'` etc 

this is theme i have loaded: 

image

**Comment by robertdavidwest** [comment]
App Bar: 

not logged in :

image


logged in :

image

image

**Comment by robertdavidwest** [comment]
All projects styling: 

image

**Comment by robertdavidwest** [comment]
View when no projects: 
image

**Comment by robertdavidwest** [comment]
footer : 
image

**Review by philbertani — APPROVED** [review]
nice one

**Pull request merged**
